language: go

go:
  - "1.12"

# clone the most recent commit only
git:
  depth: 1

install: true

# run test
script:
  - make
  - sudo make install
  - make test

branches:
  only:
  - master
  - develop
  - /^release-.*$/

# no deploy
